services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
  app:
    build: .
    restart: always
    ports:
      - ${PORT}:3000
    depends_on:
      - db
